### ISSUE TITLE
Add hooks imports

### ISSUE THREAD

**Issue by Hauglid** [devmuaz/flutter-hooks-snippets#1]
Very nice extension. Just started using it but it seems very functional 👍

I would really like to have imports when using hookW (and probably the others but I haven't used them yet.)

```
import 'package:flutter/material.dart';
import 'package:flutter_hooks/flutter_hooks.dart';
```

**Comment by devmuaz** [comment]
Hi @Hauglid, Thanks for opening this issue and I apologies for being too late to respond to this matter.
Actually, it a very good idea I mean why not, I'll start adding them and once I finish it..  I'll let you know here, I'm gonna let this one open until I release a version with the enhancements you mentioned above.

Again, Thanks for making things awesome mate!

**Comment by devmuaz** [comment]
Hi @Hauglid,
Flutter hooks imports have been added in `v0.0.5`, you can update the extensions and start using it.
